language: r
cache: packages

r_packages:
  - devtools

r_github_packages:
  - tlverse/tlverse

before_script:
  - chmod +x ./handbook/_build.sh
  - chmod +x ./handbook/_deploy.sh

after_success:
  - cd handbook
  - ./_build.sh
  - test $TRAVIS_BRANCH = "master" &&
    ./_deploy.sh

